export const IPC_MESSAGE = {
  PING: 'ping',
  GAME_GET: 'game.get',
  GAME_PICK: 'game.pick',
  GAME_RUNNING: 'game.running',
  CATALOG_MAPS: 'catalog.maps',
  CATALOG_SOUNDS: 'catalog.sounds',
  CATALOG_SKINS: 'catalog.skins',
  CATALOG_BY_IDS: 'catalog.byIds',
  BROWSER_OPEN: 'browser.open',
  FOLDER_OPEN: 'folder.open',
  DOWNLOADS_OPEN: 'downloads.open',
  MOD_DOWNLOAD: 'mod.download',
  MOD_APPLY: 'mod.apply',
  MOD_RESET: 'mod.reset',
  MOD_MAP_NAMES: 'mod.mapNames',
  LOADOUT_GET: 'loadout.get',
  MODS_RESET_ALL: 'mods.resetAll',
  MODS_REAPPLY: 'mods.reapply',
  SOUND_DOWNLOAD: 'sound.download',
  SKIN_DOWNLOAD: 'skin.download',
  DOWNLOADS_LIST: 'downloads.list',
  DOWNLOADS_DELETE: 'downloads.delete',
  DOWNLOAD_PROGRESS: 'download.progress',
  MUSIC_APPLY: 'music.apply',
  MUSIC_TRACKS: 'music.tracks',
  MUSIC_REPLACE: 'music.replace',
  MUSIC_PICK: 'music.pick',
  MODS_RANKED_SAFE: 'mods.rankedSafe',
  CONFIGS_LIST: 'configs.list',
  CONFIGS_SAVE: 'configs.save',
  CONFIGS_LOAD: 'configs.load',
  CONFIGS_DELETE: 'configs.delete',
} as const;

export type IpcMessageType = typeof IPC_MESSAGE[keyof typeof IPC_MESSAGE];
